site_name: IT 뒷담
site_url: https://tnstory.github.io/
site_description: "IT 뒷담은 it 트랜드를 가볍게 다뤄보는 공간입니다."
site_author: "MinBae Lee"


theme:
  name: material
  custom_dir: overrides  # docs/overrides 아님!
  favicon: assets/images/favicon_io/favicon.ico
  logo: assets/images/favicon_io/android-chrome-192x192.png
  language: ko
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.copy
  code:
    highlight_theme: github-dark

extra:
  meta:
    description: "IT 뒷담은 it 트랜드를 가볍게 다뤄보는 공간입니다."
    keywords: "IT 뒷담, Kubernetes, Cloud, GitOps, CNCF, AI, SpringBoot"
    author: "MinBae Lee"

  social:
    - icon: fontawesome/brands/github
      link: https://tnstory.github.io/
      name: GitHub
  alternate:
    - name: 한국어
      link: /
      lang: ko
    - name: English
      link: /en/
      lang: en


extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      languages:
        - locale: ko
          name: 한국어
          default: true
          build: true
          site_name: "IT 뒷담"
        - locale: en
          name: English
          build: true
          site_name: "IT behind"
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
  - table-reader

    
  # - sitemap:
  #     changefreq: monthly
  #     priority: 0.5

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: index.md
  - PoC:
      - Overview: PoC.md
      - Kubernetes Service Discovery Performance: PoC/Kubernetes_ServiceDiscovery_Performance_PoC.md
      - Docker Image Optimization Guide: PoC/Docker_Image_Optimization_Guide.md
  - GreenHouse:
      - Overview: GreenHouse.md
  - About Me: aboutme.md


